### ISSUE TITLE
No link to Tree-Based Move Manager

### ISSUE THREAD

**Issue by Naclador** [michitux/dokuwiki-plugin-move#102]
Contrary to documentation, I do not get a link to the Tree-Based Move Manager in the "Move current page or namespace" page. How else can I access the Tree-Based Move Manager?

**Comment by rgleason** [comment]
You may not have the rights to do that. Are you just a user?

**Comment by Naclador** [comment]
No, I am Admin. I am using dokuwiki Release 2016-06-26a "Elenor of Tsort". Might it be a translation issue? Because I am using the german version.

**Comment by rgleason** [comment]
I think it could be something like that, because It shows for me. 
ADMIN
Down at bottom of page Additional Plugins
Move Pages and Namespaces

--------------
 All links to and from the pages that are moved will be updated to reflect the new location and/or name.
Alternatively to this simple form you can manage complex restructuring of your wiki using the tree-based move manager.  <<<---LOOK for LINK HERE

Then the Move Manager Fields are below.
--------------------

The layout and functionality of this could all be improved. I think there should be some Icons or menu popup for Managers and Admin from the main window.   But this is all dependent on the Dokuwiki interface development, not the Plugins I think.

**Comment by Naclador** [comment]
Well the plugin shows up and I can use the simple Move form, but no link to the tree view for me. I'll see if I can get the English version running.

**Comment by michitux** [comment]
The problem is most likely that some plugin is breaking the JavaScript code (the link is only visible when JavaScript is working). Some things to try: look at the error console of your browser, disable JavaScript compression in the DokuWiki settings (which should give a more meaningful error message).

**Comment by Naclador** [comment]
No, JavaScript is working. I have set everything to English and still get no link anywhere.

Screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/20790571/23455012/81392b92-fe6e-11e6-9fac-b0fdb7097732.png)

**Comment by michitux** [comment]
How do you know JavaScript is working?

**Comment by Naclador** [comment]
Because JavaScript is working on all other websites and NoScript is off. Is there a way of testing it specifically in Dokuwiki?

**Comment by Naclador** [comment]
I just looked into the page's source code and found the link there. But it does not show up in the browser window for some weird reason.

**Comment by Naclador** [comment]
Guess JavaScript is not working somehow, I copied the link into the browser address field and got just the Title for the tree-based move, but nothing else. 
![grafik](https://cloud.githubusercontent.com/assets/20790571/23457209/433279d0-fe77-11e6-8ca8-b591005acf05.png)

**Comment by michitux** [comment]
I did not mean that JavaScript is not working in your browser, but rather that e.g. some plugin contains broken JavaScript code and this unfortunately also breaks all other plugins.

**Comment by Naclador** [comment]
Well, this is entirely possible. Are there any plugins notorious for such problems? Otherwise I guess I'll have to deactivate them one by one and try.

**Comment by michitux** [comment]
You can find out which plugin creates the problem by turning on the [allowdebug](https://www.dokuwiki.org/config:allowdebug) configuration option (remember to turn it off again later). Then you should get an error message that contains a file name which should give you a hint what plugin is causing problem in the console of the developer tools of your browser, e.g. in [Firefox](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console) or [Chrome](https://developers.google.com/web/tools/chrome-devtools/).

**Comment by Naclador** [comment]
Thank you, I'll try that.

**Comment by Naclador** [comment]
Strange. As soon as I check "Allow Debug", the link appears without any error message and the Move Manager works nicely. But when I uncheck "Allow Debug" I am back with no link.

**Comment by michitux** [comment]
@Naclador It is expected that with "Allow Debug" it works because this kind of isolates the code of the different plugins. However, an error message should still be generated in the console of the developer tools.

**Comment by Naclador** [comment]
Thank you very much, michitux! 
Indeed, there have been error messages in the console, I have been looking somewhere else. I have deleted some old and buggy plugins I had inherited from the former admin, and now "Move" works exactly as it should.
