### ISSUE TITLE
Rename Page button doesn't work

### ISSUE THREAD

**Issue by bradbulger** [michitux/dokuwiki-plugin-move#150]
it sends me to the current page + '?do=menuitem', producing an error, "Action unknown: menuitem"

**Comment by michitux** [comment]
I can confirm this problem in the mobile view with the drop-down menu. In the regular view, this is probably due to problems with (inline) JavaScript not being executed.

**Comment by fnook** [comment]
I also have this issue - is there a fix?

**Comment by LeonStaufer** [comment]
The error occurs if there is no event listener on the link. For the event listener to be added, the element must have the `plugin_move_page` class, as explained [here](https://github.com/michitux/dokuwiki-plugin-move/blob/master/action/rename.php#L134). 

I was able to resolve the issue by adding that class, as the plugin then automatically attaches the event handler and everything works as usual.

**Comment by sokolgeo** [comment]
The problem is still here with the current stable Dokuwiki 2020-07-29 "Hogfather" and Move plugin version 2018-04-30.

In mobile view attempt to use the drop-down menu to rename current item leads to the error  "Action unknown: menuitem".

Any chance this gets fixed, please? Or is the problem on mobile template side?
