### ISSUE TITLE
After moving a sub-directory it appears as a main-directory

### ISSUE THREAD

**Issue by Michael-FFM** [michitux/dokuwiki-plugin-move#197]
I have the following sub-directory: "images_xyz". I mark this sub-directory and move it to the main-directory "techn._grundlagen".
But the sub-directory appears as the new main-directory.
In my opinion this is an error!

Dokuwiki-version: Release 2020-07-29 "Hogfather"
Attachment: 2 screenshots

![Error_Move_plugin_Part_1](https://user-images.githubusercontent.com/78362424/106467669-45493200-649d-11eb-8da8-c03bb4b83436.jpg)
![Error_Move_Plugin_Part_2](https://user-images.githubusercontent.com/78362424/106467704-52662100-649d-11eb-9686-60f6e6a69b26.jpg)

**Comment by michitux** [comment]
To move a folder below another folder, that other folder needs to be opened (arrow pointing down instead of right). I.e., before moving `bilder_xyz`, you need to first click on `techn._grundlagen` to open it. I hope that explanation helps. I agree this could be more intuitive, but that's how the current implementation works.

**Comment by Michael-FFM** [comment]
Thank you for the explanation. The procedure is now clear.
The Move plugin is a great help when you want to make changes in your Dokuwiki.
Especially great is the preview function. With it you can check exactly if the move runs as you want it to.
