### ISSUE TITLE
LESS-bug: @ini_text incompatible with bootstrap template

### ISSUE THREAD

**Issue by franzi91** [michitux/dokuwiki-plugin-move#44]
Hey there,

I'm currently having trouble with using your plugin with my bootstrap-template. My template does not provide less variables, but your style.less calls the @ini_text at line 24. So I got an error message. Fixed this with replacing it by the color code directly, but this might be overwritten with the next update. So maybe you can use a local color code here.

Thanks
Franzi

**Comment by michitux** [comment]
DokuWiki creates less variables automatically from the values specified in `style.ini` in the template. For example `__text__` becomes `@ini_text`. `__text__` is a [guaranteed color placeholder](https://www.dokuwiki.org/devel:style.ini#guaranteed_color_placeholders), therefore the move plugin can expect that `@ini_text` is defined. Therefore the problem here is the template and not the plugin as far as I've understood so far. Could you please check if `__text__` is defined in your `style.ini`?

**Comment by michitux** [comment]
Closing because there was no feedback and because this is not an issue of the move plugin.
