### ISSUE TITLE
Move for Non-Admins

### ISSUE THREAD

**Issue by fabb** [michitux/dokuwiki-plugin-move#65]
Thank you for this plugin, this is something really missing from Dokuwiki.

Your plugin seems the only one able to update links too. Unfortunately our users cannot access the Move functionality as it is only available for Admins. Is there a way to activate the feature for regular users too? It would make sense, as they already have the permissions to create and delete pages.
If not - would it be possible to add this feature to this plugin?

**Comment by misant** [comment]
I am asking for that too. There is option to enable page renaming for list of users, but it doesn`t work.

**Comment by rnck** [comment]
On the settings page, your can specify user groups which should be allowed to use renaming and even the tree-based move manager. This worked for me:

![bildschirmfoto 2016-04-29 um 08 23 41](https://cloud.githubusercontent.com/assets/165663/14909484/68f7bd30-0de4-11e6-864d-074a866ef885.png)

Don't forget to add the users to the allowed group.

**Comment by misant** [comment]
rnck, I use LDAP authorization for Doku, it works fine. But when I configure mentioned move access rights nothing happens.

**Comment by rnck** [comment]
Ok, in an installation with internal authorization my solution worked. I have another DokuWiki with AD-based authorization and I can confirm it does not work there.

So, this bug(?) seems to be related to the auth method used. Perhaps, because user-groups (AD/LDAP-based) are not directly available in DokuWiki? But page or namespace restrictions based on AD-groups work for me.

**Comment by misant** [comment]
rnck, yes, all kind of Doku ACLs not related with Move plugin are working fine.

**Comment by splitbrain** [comment]
The single page rename feature is available to all groups and users listed in the `allowrename` option.

The admin interface and tree move manager are only available to admins and managers. Since those are implemented as admin plugin there is no way around that. If you trust your users enough to give them such a powerful tool, you could simply make them all managers.
