### ISSUE TITLE
Conflict with Bootstrap Simplified Template

### ISSUE THREAD

**Issue by itivet** [michitux/dokuwiki-plugin-move#68]
Right after installation an error message is shown:

> A fatal error occured during compilation of the CSS files [...]
> expected color value: failed at 'border: 1px dashed lighten(@ini_text, 30%);' in /lib/plugins/move/style.less at line 24

**Comment by vinzv** [comment]
+1

**Comment by michitux** [comment]
This is because this template does not define the [guaranteed color placeholders](https://www.dokuwiki.org/devel:style.ini#guaranteed_color_placeholders). Citing that page: "All templates have to implement these at least". Therefore I would say that this is an issue of the template, though I also raised an issue in DokuWiki (splitbrain/dokuwiki#1792) because I think DokuWiki could do a better job at preventing such issues.

**Comment by rgleason** [comment]
We are using a bootstrap3 template and it seems to be working fine, so far. https://opencpn.org  then pick BOOKS.  The bootstrap3 template has many settings, perhaps one of them will fix this problem?
