### ISSUE TITLE
Compatibility issue with Release 2016-06-26 "Elenor of Tsort"

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [michitux/dokuwiki-plugin-move#72]
doku.php?do=admin

Warning: Declaration of admin_plugin_move::getMenuText() should be compatible with DokuWiki_Admin_Plugin::getMenuText($language) in /home/sfdaasdf2ddddf/gfail.net/dokuwiki/lib/plugins/move/admin.php on line 276

**Comment by jkldgoefgkljefogeg** [comment]
functionality broken, when I tried to move a page I got

> Fatal error: Call to undefined function getRevisions() in lib/plugins/move/helper.php on line 402

**Comment by TheTomcat14** [comment]
This bug seems to be caused by the removal of deprecated code from the dokuwiki codebase.
(reference to the commit https://github.com/splitbrain/dokuwiki/commit/aa13c9aa4552dbb0baa04be45d13ef62f178b154)

As a quick & dirty fix I added the code for getRevisions() to the file lib/plugins/move/helper.php (at the end of the file, outside the class declaration).
Adding the deprecated code to the plugin "should" protect the functionality from future dokuwiki updates.

A permanent/better solution would be to fix the 2 getRevisions() calls made in the plugin.

Code pasted at the very end of the file lib/plugins/move/helper.php

`
function getRevisions($id, $first, $num, $chunk_size = 8192, $media = false) {
    dbg_deprecated('class PageChangeLog or class MediaChangelog');
    if($media) {
        $changelog = new MediaChangeLog($id, $chunk_size);
    } else {
        $changelog = new PageChangeLog($id, $chunk_size);
    }
    return $changelog->getRevisions($first, $num);
}
`

**Comment by micgro42** [comment]
Your version of the plugin is outdated. Please update the move plugin to the current version.

**Comment by jkldgoefgkljefogeg** [comment]
How did you determine the version I have is outdated? Did you read the comment above?

**Comment by micgro42** [comment]
``lib/plugins/move/admin.php`` and ``lib/plugins/move/helper.php`` do not exist in the current version of the plugin.

**Comment by jkldgoefgkljefogeg** [comment]
I am confused. These files are not in 2015-10-18 tag either. And the version from dokuwiki store has never been updated?
plugin.info.txt can probably get some update.

**Comment by jkldgoefgkljefogeg** [comment]
There seems to be some issue with the dokuwiki extension manager. I reinstalled this extension but there were still files modified in 2014 (admin.php, helper.php, even .gitignore). Uninstall and install the plugin solved the problem. Sorry for the noise.

**Comment by micgro42** [comment]
It seems one must explicitly tell the extension manger to remove those old files. The linked pull request should solve this problem in the future.
