### ISSUE TITLE
Possibility to move a page to 'bin' (delete button)?

### ISSUE THREAD

**Issue by SonoDavid** [michitux/dokuwiki-plugin-move#79]
Hello, I'm looking for a good way to remove pages. Especially new users don't know how to remove pages in the DokuWiki and I would like a user-friendly way to remove a page from the wiki.
Would it be possible to add a 'bin' space which is unreachable for all users, except admins, where old pages can be moved to.
An extra bonus would be a separate 'delete' button to move pages to the bin.

**Comment by rgleason** [comment]
Why not create a "bin" page from the URL line. Or just Create a New Page.  Then MOVE your deleted pages to it?
When you move you may not want the links "fixed"
I like that Idea and may do it.
Let use know how it works.

**Comment by splitbrain** [comment]
I don't think this makes much sense. There is no sensible difference between emptying a page and deleting it. That's why DokuWiki deletes pages the way it does.

Pages can easily be restored again using the revisions feature of DokuWiki. No need for an extra "bin" aka "trash" namespace.

If the usual way to delete pages is not discoverable enough for your users, adding a delete button might be sensible but does not fit within the scope of this plugin.

As an admin you can of course use this plugin to move pages into a namespace not accessible to normal users.
