### ISSUE TITLE
Noob Question

### ISSUE THREAD

**Issue by asheenlevrai** [michitux/dokuwiki-plugin-move#95]
Hello,

The doc states:

> Support for other plugins
> 
> The move plugin allows plugins to move their own data and to adapt their syntax when a page or media file is moved. Currently the following plugins support this:
> 
>     include
>     struct
> 
> Plugins not explicitly stating their compatibility are most probably not adjusted.
> 

What kind of plugin should I be carefull about (I already use quite some of them).

Thank you very much in advance for your help.
Best,
-a-

**Comment by rgleason** [comment]
We are using indexmenu with Move.  It seems to work, including the Tree-based move.
However the Tree based move seems to be limited to moving 2 tiers down only.

**Comment by asheenlevrai** [comment]
I am sorry I did not understand your answer.

My original question was : what kind of plugin should I be careful about? For instance, I doubt a plugin such as AutoLogOff (https://www.dokuwiki.org/plugin:autologoff) should be of any concern since it has nothing to do with links or the structure of the wiki. However, I wonder if plugins such as Note (https://www.dokuwiki.org/plugin:note) should be carefully examined since it may interact with page links and so on.

Briefly, what type of feature in a custom plugin is susceptible to be problematic for the Move plugin to handle?

Thank you very much in advance for your help.

Best,
-a-

**Comment by michitux** [comment]
Most syntax plugins (and in fact most plugins that are available) are harmless, i.e., the worst thing that can happen is that possibly some (or all) links are not adapted. There are some exceptions to that:

* Plugins that attach data to pages that is not saved in the wiki text. Examples are the [tagging](https://www.dokuwiki.org/plugin:tagging) plugin or [blogtng](https://www.dokuwiki.org/plugin:tagging). There you might lose the data of the moved pages. Each of these plugins needs to support the move plugin. For example the [struct](https://www.dokuwiki.org/plugin:struct) plugin has added explicit support.
* Plugins that modify the page content without using a syntax plugin. Some background on this: The plain text of the page is parsed by DokuWiki. Plugins can register their syntax in the DokuWiki parser and are called when their syntax is found. Plugins using this mechanism are no problem at all. However, some plugins modify the page content **before** it is parsed which is a problem for the move plugin. This is usually not so easy to detect without looking at the code. A warning sign is, that a plugin somehow modifies the content of a page without using a special syntax. Examples are all kinds of plugins that automatically add links to the page content like [autolink2](https://www.dokuwiki.org/plugin:autolink2). Also the [snippets](https://www.dokuwiki.org/plugin:snippets) plugin is incompatible because it inserts the snippets while reading the page. A more generalized warning sign can be that a plugin allows to insert snippets containing arbitrary syntax that directly interacts with the syntax on the page (e.g. allowing you to insert single rows in a table). Different from that are plugins like the [include](https://www.dokuwiki.org/plugin:include) plugin that are regular syntax plugin and do not insert anything on a text level but only after the text has already been parsed.

**Comment by rgleason** [comment]
asheenlevrai  Excellent question.  and Michael this answer is a keeper I think, lots of experience behind it.

How can we get this in the right place for users to see it in the documentation because its the same kinds of questions/fears I had.

**Comment by splitbrain** [comment]
@rgleason just adjust the wiki page as you see fit to make it understandable for end users.
